import 'dart:ui';

class ColorRes {
  static const Color app = Color(0xFF667EE2);
  static const Color button = Color(0xFFFCA311);
  static const Color transparent = Color(0x00000000);
  static const Color crystalBlue = Color(0xff58AFFF);
  static const Color darkSkyBlue = Color(0xff4D92E2);
  static const Color havelockBlue = Color(0xff4E93E2);
  static const Color tuftsBlue = Color(0xFFFCA311);
  static const Color tuftsBlue100 = Color(0xff4378C8);
  static const Color white = Color(0xffFFFFFF);
  static const Color black = Color(0xff000000);
  static const Color darkJungleGreen = Color(0xff202020);
  static const Color iceberg = Color(0xffDDEEFE);
  static const Color bittersweet = Color(0xffFF6D6D);
  static const Color lightRed = Color(0xffFF4848);
  static const Color ferrariRed = Color(0xffFF1616);
  static const Color darkGreen = Color(0xff038F2A);
  static const Color irishGreen = Color(0xff008E1F);
  static const Color mediumGreen = Color(0xff00BE2A);
  static const Color fadedOrange = Color(0xffF0933E);
  static const Color pastelOrange = Color(0xffFE974C);
  static const Color mangoOrange = Color(0xffFF842B);
  static const Color pinkLace = Color(0xffFFDFDF);
  static const Color snowDrift = Color(0xffF9F9F9);
  static const Color whiteSmoke = Color(0xffF4F4F4);
  static const Color aquaHaze = Color(0xffF3F3F3);
  static const Color dawnPink = Color(0xffECECEC);
  static const Color softPeach = Color(0xffEFEFEF);
  static const Color lightGrey = Color(0xffDADADA);
  static const Color silver = Color(0xffC6C6C6);
  static const Color greyShade300 = Color(0xffE0E0E0);
  static const Color nobel = Color(0xffB3B3B3);
  static const Color silverChalice = Color(0xffACACAC);
  static const Color charcoalGrey = Color(0xff414141);
  static const Color davyGrey = Color(0xff575757);
  static const Color smokeyGrey = Color(0xff6F6F6F);
  static const Color battleshipGrey = Color(0xff848484);
  static const Color grey = Color(0xff909090);
  static const Color mercury = Color(0xffE6E6E6);
  static const Color blueLagoon = Color(0x77E6E8EB);
}
